backend:
  name: git-gateway
  branch: main

media_folder: "imagens"
public_folder: "/imagens"
media_library:
  name: "cloudinary"
  config:
    cloud_name: "seu_cloud_name"
    api_key: "sua_api_key"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - name: "main_content"
        label: "Conteúdo Principal"
        file: "_data/site_content.json"
        description: "Edite os principais textos, imagens e pacotes do site aqui."
        fields:
          - {label: "Texto do Logo", name: "logo_text", widget: "string", hint: "O nome que aparece no canto superior esquerdo."}
          - {label: "Título Principal", name: "hero_title", widget: "string", hint: "O título grande no topo da página."}
          - {label: "Subtítulo Principal", name: "hero_subtitle", widget: "text", hint: "O texto de apoio abaixo do título principal."}
          - name: "packages"
            label: "Pacotes de Serviços"
            label_singular: "Pacote"
            widget: "list"
            fields:
              - {label: "Nome do Pacote", name: "name", widget: "string"}
              - {label: "Descrição", name: "description", widget: "string"}
              - {label: "Preço", name: "price", widget: "string"}
              - name: "features"
                label: "Funcionalidades"
                label_singular: "Funcionalidade"
                widget: "list"
                field: { label: "Funcionalidade", name: "feature", widget: "string"}
              - {label: "Recomendado?", name: "recommended", widget: "boolean", default: false}
          - {label: "Foto de Perfil (Sobre)", name: "about_photo", widget: "image"}

  - name: "portfolio"
    label: "Portfólio"
    folder: "_data/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Categoria", name: "category", widget: "select", options: ["residencial", "comercial"]}
      - {label: "Imagem", name: "image", widget: "image"}

