backend:
  name: git-gateway
  branch: main

media_folder: "imagens"
public_folder: "/imagens"
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey # Substitua pela sua chave pública do Uploadcare

collections:
  - name: "settings"
    label: "Configurações Gerais"
    files:
      - name: "main_content"
        label: "Conteúdo Principal"
        file: "_data/site_content.json"
        description: "Edite os principais textos, imagens e pacotes do site aqui."
        fields:
          - name: header
            label: "Cabeçalho"
            widget: "object"
            fields:
              - name: logo_type
                label: "Tipo de Logo"
                widget: "select"
                options: ["text", "image"]
                default: "text"
              - name: logo_text
                label: "Texto do Logo"
                widget: "string"
                hint: "O nome que aparece no canto superior esquerdo."
                required: false
              - name: logo_image
                label: "Imagem do Logo"
                widget: "image"
                required: false
          - name: hero
            label: "Secção Principal (Hero)"
            widget: "object"
            fields:
              - {label: "Título Principal", name: "title", widget: "string"}
              - {label: "Subtítulo Principal", name: "subtitle", widget: "text"}
          - name: packages
            label: "Pacotes de Serviços"
            label_singular: "Pacote"
            widget: "list"
            fields:
              - {label: "Nome do Pacote", name: "name", widget: "string"}
              - {label: "Descrição", name: "description", widget: "string"}
              - {label: "Preço", name: "price", widget: "string"}
              - name: "features"
                label: "Funcionalidades"
                label_singular: "Funcionalidade"
                widget: "list"
                field: { label: "Funcionalidade", name: "feature", widget: "string"}
              - {label: "Recomendado?", name: "recommended", widget: "boolean", default: false}
          - name: about
            label: "Secção Sobre"
            widget: "object"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Nome e Cargo", name: "name", widget: "string"}
              - {label: "Biografia", name: "bio", widget: "text"}
              - {label: "Foto de Perfil", name: "photo", widget: "image"}

  - name: "portfolio"
    label: "Portfólio"
    label_singular: "Projeto"
    folder: "_portfolio" # Usaremos uma pasta para cada projeto
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Categoria", name: "category", widget: "select", options: ["residencial", "comercial"]}
      - {label: "Imagem", name: "image", widget: "image"}

