# Backend configuration for Netlify with Git Gateway
backend:
  name: git-gateway
  branch: main # Or your default branch

# URL for a custom logo in the CMS login and header
logo_url: https://placehold.co/150x50/FFFFFF/0A2463?text=AC+Engenharia

# Media files configuration
media_folder: "imagens" # Where to upload the files
public_folder: "/imagens" # The src attribute for the uploaded media

# This collection uses the "files" type. It's perfect for managing different sections
# of the site where each section's content is stored in a single, separate JSON file.
# ALL file-based collections are now grouped here, which fixes the validation error.
collections:
  - name: "content"
    label: "Conteúdo do Site"
    files:
      - label: "1. Configurações Gerais"
        name: "config"
        file: "_data/config.json"
        description: "Configurações globais como logo e dados da proposta."
        fields:
          - { label: "Cabeçalho", name: "header", widget: "object", fields: [ { label: "Texto do Logo", name: "logo_text", widget: "string" } ] }
          - { label: "Dados da Proposta (Padrão)", name: "proposal_details", widget: "object", fields: [ { label: "Texto de Validade", name: "validity_text", widget: "string" }, { label: "Dias de Validade", name: "validity_days", widget: "number" } ] }
      
      - label: "2. Seção Hero (Topo)"
        name: "hero"
        file: "_data/hero.json"
        description: "A primeira seção que o cliente vê."
        fields:
          - { label: "Título Principal", name: "title", widget: "string" }
          - { label: "Subtítulo", name: "subtitle", widget: "text" }

      - label: "3. Sobre o Profissional"
        name: "sobre"
        file: "_data/sobre.json"
        description: "Sua foto, nome e biografia."
        fields:
          - { label: "Sua Foto", name: "photo", widget: "image" }
          - { label: "Nome e Cargo", name: "name", widget: "string" }
          - { label: "Biografia", name: "bio", widget: "text" }
      
      - label: "4. Soluções (Abas)"
        name: "solutions"
        file: "_data/solutions.json"
        description: "Os 4 tipos de projetos oferecidos, agora com imagens."
        fields:
          - label: "Projeto Arquitetônico"
            name: "arquitetonico"
            widget: "object"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Ícone", name: "icon", widget: "string"}
              - {label: "Descrição", name: "description", widget: "text"}
              - {label: "Imagem de Destaque", name: "image", widget: "image"}
              - {label: "Entregáveis", name: "deliverables", widget: "list", field: {label: "Item", name: "item", widget: "string"}}
          - label: "Projeto Estrutural"
            name: "estrutural"
            widget: "object"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Ícone", name: "icon", widget: "string"}
              - {label: "Descrição", name: "description", widget: "text"}
              - {label: "Imagem de Destaque", name: "image", widget: "image"}
              - {label: "Entregáveis", name: "deliverables", widget: "list", field: {label: "Item", name: "item", widget: "string"}}
          - label: "Projeto Hidrossanitário"
            name: "hidrossanitario"
            widget: "object"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Ícone", name: "icon", widget: "string"}
              - {label: "Descrição", name: "description", widget: "text"}
              - {label: "Imagem de Destaque", name: "image", widget: "image"}
              - {label: "Entregáveis", name: "deliverables", widget: "list", field: {label: "Item", name: "item", widget: "string"}}
          - label: "Projeto Elétrico"
            name: "eletrico"
            widget: "object"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Ícone", name: "icon", widget: "string"}
              - {label: "Descrição", name: "description", widget: "text"}
              - {label: "Imagem de Destaque", name: "image", widget: "image"}
              - {label: "Entregáveis", name: "deliverables", widget: "list", field: {label: "Item", name: "item", widget: "string"}}

      - label: "5. Comparativo de Valor (ROI)"
        name: "roi"
        file: "_data/roi.json"
        description: "A tabela de comparação 'Com vs Sem Engenheiro'."
        fields:
          - name: "items"
            label: "Itens da Tabela"
            widget: "list"
            fields:
              - { label: "Ícone (Phosphor Icons)", name: "icon", widget: "string" }
              - { label: "Critério", name: "criteria", widget: "string" }
              - { label: "Sem Profissional", name: "without_professional", widget: "string" }
              - { label: "Com Engenharia", name: "with_professional", widget: "string" }
            
      - label: "6. Processo de Trabalho"
        name: "timeline"
        file: "_data/timeline.json"
        description: "As etapas do seu processo."
        fields:
          - name: "items"
            label: "Etapas"
            widget: "list"
            fields:
              - {label: "Título da Etapa", name: "title", widget: "string"}
              - {label: "Descrição", name: "description", widget: "text"}
      
      - label: "7. Portfólio"
        name: "portfolio"
        file: "_data/portfolio.json"
        description: "Gerencie todos os projetos do seu portfólio aqui."
        fields:
          - name: "items"
            label: "Projetos do Portfólio"
            widget: "list"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Categoria", name: "category", widget: "select", options: ["residencial", "comercial"]}
              - {label: "Imagem", name: "image", widget: "image"}

      - label: "8. Exemplos de Entregáveis"
        name: "entregaveis"
        file: "_data/entregaveis.json"
        description: "Gerencie as imagens e títulos da seção 'O Que Você Recebe'."
        fields:
          - name: "items"
            label: "Itens Entregáveis"
            widget: "list"
            fields:
              - {label: "Imagem do Entregável", name: "image", widget: "image"}
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Categoria", name: "category", widget: "string"}

      - label: "9. Garantias"
        name: "guarantees"
        file: "_data/guaranteis.json"
        description: "As garantias que você oferece."
        fields:
          - name: "items"
            label: "Itens de Garantia"
            widget: "list"
            fields:
              - {label: "Ícone", name: "icon", widget: "string"}
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Descrição", name: "description", widget: "text"}

      - label: "10. Depoimentos"
        name: "testimonials"
        file: "_data/testimonials.json"
        description: "Depoimentos de clientes."
        fields:
          - name: "items"
            label: "Depoimentos"
            widget: "list"
            fields:
              - {label: "Texto", name: "text", widget: "text"}
              - {label: "Autor", name: "author", widget: "string"}

      - label: "11. Pacotes de Serviços"
        name: "packages"
        file: "_data/packages.json"
        description: "Os planos de investimento que você oferece."
        fields:
          - name: "items"
            label: "Pacotes"
            widget: "list"
            fields:
              - { label: "Nome do Pacote", name: "name", widget: "string" }
              - { label: "Descrição", name: "description", widget: "string" }
              - { label: "Preço", name: "price", widget: "string" }
              - { label: "Funcionalidades", name: "features", widget: "list", field: { label: "Item", name: "feature", widget: "string" } }
              - { label: "É Recomendado?", name: "recommended", widget: "boolean", default: false }

      - label: "12. Perguntas Frequentes (FAQ)"
        name: "faq"
        file: "_data/faq.json"
        description: "As perguntas e respostas mais comuns."
        fields:
          - name: "items"
            label: "Perguntas"
            widget: "list"
            fields:
              - {label: "Pergunta", name: "question", widget: "string"}
              - {label: "Resposta", name: "answer", widget: "text"}

