backend:
  name: git-gateway
  branch: main

media_folder: "imagens"
public_folder: "/imagens"

collections:
  - name: "settings"
    label: "Conteúdo do Site"
    files:
      - name: "general"
        label: "Textos e Configurações Principais"
        file: "_data/site_content.json"
        description: "Edite os principais textos, imagens e seções do site aqui."
        fields:
          - { name: "header", label: "Cabeçalho", widget: "object", fields: [ { name: "logo_type", label: "Tipo de Logo", widget: "select", options: ["text", "image"], default: "text" }, { label: "Texto do Logo", name: "logo_text", widget: "string", required: false }, { label: "Imagem do Logo", name: "logo_image", widget: "image", required: false } ] }
          
          - name: "proposal_details"
            label: "Dados da Proposta (Valores Padrão)"
            widget: "object"
            fields:
              - { label: "Título da Seção", name: "title", widget: "string", default: "Proposta de Soluções de Engenharia" }
              - { label: "Texto de Validade", name: "validity_text", widget: "string", default: "Validade" }
              - { label: "Número de Dias de Validade", name: "validity_days", widget: "number", default: 15 }

          - { name: "hero", label: "Seção Principal (Topo)", widget: "object", fields: [ { label: "Título", name: "title", widget: "string" }, { label: "Subtítulo", name: "subtitle", widget: "text" }, { label: "Imagem de Fundo", name: "background_image", widget: "image", required: false, hint: "Opcional. Imagem que aparecerá no fundo da seção principal."} ] }
          
          - name: "value_comparison"
            label: "Comparativo de Valor (ROI)"
            widget: "list"
            fields:
              - { label: "Nome do Ícone (Phosphor Icons)", name: "icon", widget: "string", hint: "Ex: 'currency-dollar', 'timer', 'warning'. Visite phosphoricons.com." }
              - { label: "Critério", name: "criteria", widget: "string" }
              - { label: "Resultado Sem Profissional", name: "without_professional", widget: "string" }
              - { label: "Resultado Com Engenharia Integrada", name: "with_professional", widget: "string" }

          - name: "solutions"
            label: "Soluções (Abas)"
            widget: "object"
            fields:
              - name: "arquitetonico"
                label: "Projeto Arquitetônico"
                widget: "object"
                fields:
                  - {label: "Título", name: "title", widget: "string"}
                  - {label: "Nome do Ícone (Phosphor Icons)", name: "icon", widget: "string", hint: "Ex: 'house-line'"}
                  - {label: "Descrição", name: "description", widget: "text"}
                  - {label: "Entregáveis", name: "deliverables", widget: "list", field: {label: "Item", name: "item", widget: "string"}}
              - name: "estrutural"
                label: "Projeto Estrutural"
                widget: "object"
                fields:
                  - {label: "Título", name: "title", widget: "string"}
                  - {label: "Nome do Ícone (Phosphor Icons)", name: "icon", widget: "string", hint: "Ex: 'buildings'"}
                  - {label: "Descrição", name: "description", widget: "text"}
                  - {label: "Entregáveis", name: "deliverables", widget: "list", field: {label: "Item", name: "item", widget: "string"}}
              - name: "hidrossanitario"
                label: "Projeto Hidrossanitário"
                widget: "object"
                fields:
                  - {label: "Título", name: "title", widget: "string"}
                  - {label: "Nome do Ícone (Phosphor Icons)", name: "icon", widget: "string", hint: "Ex: 'drop'"}
                  - {label: "Descrição", name: "description", widget: "text"}
                  - {label: "Entregáveis", name: "deliverables", widget: "list", field: {label: "Item", name: "item", widget: "string"}}
              - name: "eletrico"
                label: "Projeto Elétrico"
                widget: "object"
                fields:
                  - {label: "Título", name: "title", widget: "string"}
                  - {label: "Nome do Ícone (Phosphor Icons)", name: "icon", widget: "string", hint: "Ex: 'plugs'"}
                  - {label: "Descrição", name: "description", widget: "text"}
                  - {label: "Entregáveis", name: "deliverables", widget: "list", field: {label: "Item", name: "item", widget: "string"}}
          
          - { name: "sobre", label: "Seção Sobre", widget: "object", fields: [ { label: "Título", name: "title", widget: "string" }, { label: "Nome e Cargo", name: "name", widget: "string" }, { label: "Biografia", name: "bio", widget: "text" }, { label: "Foto de Perfil", name: "photo", widget: "image" } ] }
          - { name: "timeline", label: "Processo de Trabalho (Linha do Tempo)", widget: "list", fields: [ {label: "Título da Etapa", name: "title", widget: "string"}, {label: "Descrição da Etapa", name: "description", widget: "text"} ] }
          - { name: "guarantees", label: "Garantias", widget: "list", fields: [ {label: "Nome do Ícone (Phosphor Icons)", name: "icon", widget: "string", hint: "Ex: 'shield-check', 'clock', 'users-three'"}, {label: "Título", name: "title", widget: "string"}, {label: "Descrição", name: "description", widget: "text"} ] }
          - { name: "testimonials", label: "Depoimentos", widget: "list", fields: [ {label: "Texto do Depoimento", name: "text", widget: "text"}, {label: "Autor", name: "author", widget: "string"} ] }
          - name: "packages"
            label: "Pacotes de Serviços"
            widget: "list"
            fields:
              - { label: "Nome do Pacote", name: "name", widget: "string" }
              - { label: "Descrição", name: "description", widget: "string" }
              - { label: "Preço", name: "price", widget: "string" }
              - name: "features" 
                label: "Funcionalidades"
                widget: "list"
                field: { label: "Item", name: "feature", widget: "string" }
              - { label: "É Recomendado?", name: "recommended", widget: "boolean", default: false }
          - { name: "faq", label: "Perguntas Frequentes (FAQ)", widget: "list", fields: [ {label: "Pergunta", name: "question", widget: "string"}, {label: "Resposta", name: "answer", widget: "text"} ] }

  - name: "portfolio"
    label: "Portfólio"
    files:
      - name: "portfolio_items"
        label: "Projetos do Portfólio"
        file: "_data/portfolio.json"
        description: "Gerencie os itens que aparecem na galeria do portfólio."
        fields:
          - name: "items"
            label: "Projetos"
            widget: "list"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Categoria", name: "category", widget: "select", options: ["residencial", "comercial"]}
              - {label: "Imagem", name: "image", widget: "image"}
