backend:
  name: git-gateway
  branch: main

media_folder: "imagens"
public_folder: "/imagens"

collections:
  - name: "portfolio"
    label: "Portfólio"
    folder: "portfolio" # Recomendo alterar para algo como "content/portfolio" ou "_data/portfolio"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: "Categoria", name: "category", widget: "select", options: ["residencial", "comercial"]}
      - {label: "Imagem", name: "image", widget: "image", required: true}
