backend:
  name: git-gateway
  branch: main

media_folder: "imagens"
public_folder: "/imagens"

collections:
  - name: "settings"
    label: "Conteúdo do Site"
    files:
      - name: "general"
        label: "Textos e Configurações Principais"
        file: "_data/site_content.json"
        description: "Edite os principais textos, imagens e seções do site aqui."
        fields:
          - { name: "header", label: "Cabeçalho", widget: "object", fields: [ { name: "logo_type", label: "Tipo de Logo", widget: "select", options: ["text", "image"], default: "text" }, { label: "Texto do Logo", name: "logo_text", widget: "string", required: false }, { label: "Imagem do Logo", name: "logo_image", widget: "image", required: false } ] }
          - { name: "hero", label: "Seção Principal (Topo)", widget: "object", fields: [ { label: "Título", name: "title", widget: "string" }, { label: "Subtítulo", name: "subtitle", widget: "text" } ] }
          - { name: "problemas", label: "Cartões 'Riscos de um Projeto'", widget: "list", fields: [ { label: "Título", name: "title", widget: "string" }, { label: "Descrição", name: "description", widget: "text" } ] }
          - name: "solutions"
            label: "Soluções (Abas)"
            widget: "object"
            fields:
              - name: "arquitetonico"
                label: "Projeto Arquitetônico"
                widget: "object"
                fields:
                  - {label: "Ícone (Phosphor Icon)", name: "icon", widget: "string", hint: "Ex: house-line"}
                  - {label: "Título", name: "title", widget: "string"}
                  - {label: "Descrição", name: "description", widget: "text"}
                  - {label: "Entregáveis", name: "deliverables", widget: "list", field: {label: "Item", name: "item", widget: "string"}}
              - name: "estrutural"
                label: "Projeto Estrutural"
                widget: "object"
                fields:
                  - {label: "Ícone (Phosphor Icon)", name: "icon", widget: "string", hint: "Ex: hard-hat"}
                  - {label: "Título", name: "title", widget: "string"}
                  - {label: "Descrição", name: "description", widget: "text"}
                  - {label: "Entregáveis", name: "deliverables", widget: "list", field: {label: "Item", name: "item", widget: "string"}}
              - name: "hidrossanitario"
                label: "Projeto Hidrossanitário"
                widget: "object"
                fields:
                  - {label: "Ícone (Phosphor Icon)", name: "icon", widget: "string", hint: "Ex: drop"}
                  - {label: "Título", name: "title", widget: "string"}
                  - {label: "Descrição", name: "description", widget: "text"}
                  - {label: "Entregáveis", name: "deliverables", widget: "list", field: {label: "Item", name: "item", widget: "string"}}
              - name: "eletrico"
                label: "Projeto Elétrico"
                widget: "object"
                fields:
                  - {label: "Ícone (Phosphor Icon)", name: "icon", widget: "string", hint: "Ex: lightning"}
                  - {label: "Título", name: "title", widget: "string"}
                  - {label: "Descrição", name: "description", widget: "text"}
                  - {label: "Entregáveis", name: "deliverables", widget: "list", field: {label: "Item", name: "item", widget: "string"}}
          - { name: "sobre", label: "Seção Sobre", widget: "object", fields: [ { label: "Título", name: "title", widget: "string" }, { label: "Nome e Cargo", name: "name", widget: "string" }, { label: "Biografia", name: "bio", widget: "text" }, { label: "Foto de Perfil", name: "photo", widget: "image" } ] }
          - { name: "timeline", label: "Processo de Trabalho (Linha do Tempo)", widget: "list", fields: [ {label: "Título da Etapa", name: "title", widget: "string"}, {label: "Descrição da Etapa", name: "description", widget: "text"} ] }
          - { name: "guarantees", label: "Garantias", widget: "list", fields: [ {label: "Ícone (Nome do Phosphor Icon)", name: "icon", widget: "string", hint: "Use o nome do ícone do Phosphor Icons em kebab-case. Ex: shield-check, timer, users-three"}, {label: "Título", name: "title", widget: "string"}, {label: "Descrição", name: "description", widget: "text"} ] }
          - { name: "testimonials", label: "Depoimentos", widget: "list", fields: [ {label: "Texto do Depoimento", name: "text", widget: "text"}, {label: "Autor", name: "author", widget: "string"} ] }
          - { name: "packages", label: "Pacotes de Serviços", widget: "list", fields: [ { label: "Nome do Pacote", name: "name", widget: "string" }, { label: "Descrição", name: "description", widget: "string" }, { label: "Preço", name: "price", widget: "string" }, { name: "features", label: "Funcionalidades", widget: "list", field: { label: "Item", name: "feature", widget: "string" } }, { label: "É Recomendado?", name: "recommended", widget: "boolean", default: false } ] }
          - { name: "faq", label: "Perguntas Frequentes (FAQ)", widget: "list", fields: [ {label: "Pergunta", name: "question", widget: "string"}, {label: "Resposta", name: "answer", widget: "text"} ] }

  - name: "portfolio"
    label: "Portfólio"
    files:
      - name: "portfolio_items"
        label: "Projetos do Portfólio"
        file: "_data/portfolio.json"
        description: "Gerencie os itens que aparecem na galeria do portfólio."
        fields:
          - name: "items"
            label: "Projetos"
            widget: "list"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Categoria", name: "category", widget: "select", options: ["residencial", "comercial"]}
              - {label: "Imagem", name: "image", widget: "image"}

  - name: "carousel"
    label: "Carrossel de Entregáveis"
    files:
      - name: "carousel_slides"
        label: "Slides do Carrossel"
        file: "_data/carousel.json"
        description: "Gerencie os slides do carrossel da seção 'O que você recebe'."
        fields:
          - name: "slides"
            label: "Slides"
            widget: "list"
            fields:
              - {label: "Imagem do Slide", name: "image", widget: "image"}
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Categoria", name: "category", widget: "string"}

